### GET request to example server
GET http://localhost:8080/customers

###
POST http://localhost:8080/accounts/create/7
Content-Type: application/json

{
  "accountNumber": "ACC1001",
  "type": "SAVINGS",
  "balance": 5000.0
}
###

GET http://localhost:8080/accounts
###